### ISSUE TITLE
Unable to resolve "@ably/chat/react" 

### ISSUE THREAD

**Issue by ahilles107** [ably/ably-chat-js#366]
hey folks!
I'm trying to update js client from 0.1.0 to 0.2.1 in my react native (expo) app and I get this error:

```Unable to resolve "@ably/chat/react" from "src/screens/ChatRoomScreen.tsx"``` 
somehow expo does not see the new entry point.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/CHA-729) by [Unito](https://www.unito.io)

**Comment by AndyTWF** [comment]
Hey @ahilles107 !

This may because of how Expo/Metro resolves modules. There's a specific setting that has to be enabled in `metro.config.js` to allow it to properly resolve the React package:

```js
const { getDefaultConfig } = require("expo/metro-config");

const defaultConfig = getDefaultConfig(__dirname);

module.exports = {
  ...defaultConfig,
  resolver: {
    ...defaultConfig.resolver,
    unstable_enablePackageExports: true, // Enable 'exports' field in package.json,
  },
};

```

I also set `"moduleResolution": "Bundler"` in `ts.config.json` so that my VSCode could handle the exports.

Does this resolve the issue for you? If it does I'll add it to the README :)

**Comment by AndyTWF** [comment]
This issue has been quiet for a few weeks, so I will close it for now. We've now added some React Native specific guidance to the `README` and website documentation on how to handle imports.

Please re-open this issue if anything comes up, and thanks for the report!
